default:
  image: "zevrant/gitlab-runner:latest"

#job:
#  only:
#    - master@github.com/zevrant/zevrant-oauth2-service
#  extends:
#  when: delayed
#  start_in:
#  rules:
#    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
#      when: always


before_script:
  - DOCKER_LOGIN=`docker login`
  - VERSION=`aws ssm get-parameter --name zevrant-oauth2-service-VERSION`
  - VERSION=` echo $VERSION | jq .Parameter.Value`;
  - chrlen=`expr ${#VERSION} - 1`
  - VERSION=`echo $VERSION | cut -c2-$chrlen`
  - echo $VERSION

stages:
  - test
  - sonarScan
  - imageBuild
  - deploy
  - updateVersion

# sonarScan:
#   stage: sonarScan
#   script: bash gradlew sonar

test:
  stage: test
  script: bash gradlew test

imageBuild:
  stage: imageBuild
  script:
    - 'bash gradlew assemble -PprojVersion=$VERSION'
    - docker pull zevrant/zevrant-ubuntu-base:latest
    - 'docker build -t zevrant/zevrant-oauth2-service:latest -t zevrant/zevrant-oauth2-service:$VERSION --no-cache .'
    - 'docker push zevrant/zevrant-oauth2-service:latest'
    - 'docker push zevrant/zevrant-oauth2-service:$VERSION'

updateVersion:
  stage: updateVersion
  script:
    - IFS='.'
    - read -ra arr <<< "$VERSION"
    - minorVersion=$( expr ${arr[2]} + 1 )
    - aws ssm put-parameter --name zevrant-oauth2-service-VERSION --value ${arr[0]}.${arr[1]}.$minorVersion --type String --overwrite
    - echo "zevrant-oauth2-service-$VERSION"
    - git tag "zevrant-oauth2-service-$VERSION"

deploy:
  stage: deploy
  script:
    - SECRET=$(aws secretsmanager get-secret-value --secret-id /prod/rds/oauth2/password --region us-east-1)
    - SECRET=$(echo $SECRET | jq .SecretString )
    - chrlen=$(expr ${#SECRET} - 1)
    - PASSWORD=$(echo $SECRET | cut -c2-$chrlen)
    - POSTGRESQL_ROOT_PASSWORD=$PASSWORD VERSION=$VERSION AWS_SECRET_ACCESS_KEY=$SECRET_ACCESS_KEY AWS_ACCESS_KEY_ID=$ACCESS_KEY_ID docker stack deploy --with-registry-auth --compose-file docker-compose.yml zevrant-oauth2-service
