apiVersion: v1
kind: Service
metadata:
  name: zevrant-oauth2-service-db
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: zevrant-oauth2-service-db

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: zevrant-oauth2-service-db-deployment
  labels:
    app: zevrant-oauth2-service-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zevrant-oauth2-service-db
  template:
    metadata:
      labels:
        app: zevrant-oauth2-service-db
    spec:
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: database
          nfs:
            server: 192.168.0.127
            path: /i-data/420aa917/nfs/keys
      nodeSelector:
        architecture: arm
      containers:
        - name: zevrant-oauth2-service-db
          image: postgres:latest
          volumeMounts:
            - name: database
              mountPath: /storage/keys/
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: oauth-db-password
                  key: password
            - name: PGDATA
              value: /storage/keys/db/$ENVIRONMENT/oauth2/
            - name: POSTGRES_USER
              value: zevrant
            - name: POSTGRES_DB
              value: oauth2
          ports:
            - containerPort: 5432
