apiVersion: v1
kind: Service
metadata:
  name: zevrant-oauth2-service
spec:
  ports:
    - port: 443
      targetPort: 9001
  selector:
    app: zevrant-oauth2-service

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: zevrant-oauth2-service
  labels:
    app: zevrant-oauth2-service
spec:
  replicas: $REPLICAS
  selector:
    matchLabels:
      app: zevrant-oauth2-service
  template:
    metadata:
      labels:
        app: zevrant-oauth2-service
    spec:
      imagePullSecrets:
        - name: regcred
      nodeSelector:
        architecture: amd64
      containers:
        - name: zevrant-oauth2-service
          image: zevrant/zevrant-oauth2-service:$VERSION
          ports:
            - containerPort: 9001
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /zevrant-oauth2-service/actuator/health
              port: 9001
            initialDelaySeconds: 30
            failureThreshold: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /zevrant-oauth2-service/actuator/health
              port: 9001
            failureThreshold: 5
            periodSeconds: 5
            initialDelaySeconds: 30
          env:
            - name: ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: oauth-vault-credentials
                  key: username
            - name: SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: oauth-vault-credentials
                  key: password
            - name: ENVIRONMENT
              value: $ENVIRONMENT
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          resources:
            requests:
              memory: 4Gi
              cpu: 1000m
            limits:
              memory: 4Gi
              cpu: 1000m
