apiVersion: v1
kind: Service
metadata:
  name: zevrant-oauth2-service
spec:
  ports:
    - port: 443
      targetPort: 9001
  selector:
    app: zevrant-oauth2-service

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: zevrant-oauth2-service-deployment
  labels:
    app: zevrant-oauth2-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zevrant-oauth2-service
  template:
    metadata:
      labels:
        app: zevrant-oauth2-service
    spec:
      imagePullSecrets:
        - name: regcred
      nodeSelector:
        architecture: amd64
      containers:
        - name: zevrant-oauth2-service
          image: zevrant/zevrant-oauth2-service:$VERSION
          ports:
            - containerPort: 9001
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /zevrant-oauth2-service/actuator/health
              port: 9001
            initialDelaySeconds: 30
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /zevrant-oauth2-service/actuator/health
              port: 9001
            initialDelaySeconds: 30
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: zevrant-oauth2-service-aws
                  key: username
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: zevrant-oauth2-service-aws
                  key: password
            - name: ENVIRONMENT
              value: $ENVIRONMENT
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          resources:
            requests:
              memory: 1Gi
              cpu: 250m
            limits:
              memory: 4Gi
              cpu: 500m
