apiVersion: apps/v1
kind: Deployment
metadata:
  name: zevrant-oauth2-service-deployment
  labels:
    app: zevrant-oauth2-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zevrant-oauth2-service
  template:
    metadata:
      labels:
        app: zevrant-oauth2-service
    spec:
      imagePullSecrets:
        - name: regcred
      nodeSelector:
        use: this
      containers:
        - name: zevrant-oauth2-service
          image: zevrant/zevrant-oauth2-service:$VERSION
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-access-key
                  key: aws-access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret-key
                  key: aws-secret-key
            - name: ENVIRONMENT
              value: $ENVIRONMENT
          ports:
            - containerPort: 9001
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /zevrant-oauth2-service/actuator/health
              port: 9001
            initialDelaySeconds: 10
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /zevrant-oauth2-service/actuator/health
              port: 9001
            initialDelaySeconds: 10
