version: '3.5'
services:
  zevrant-oauth2-service:
    networks:
      - microservices
      - secret
    ports:
      - "9001:9001"
    depends_on:
      - zevrant-oauth2-service-db
    image: zevrant/zevrant-oauth2-service:${VERSION}
    deploy:
      placement:
        constraints:
          - node.role == worker
    environment:
      VERSION:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      AWS_DEFAULT_REGION: 'us-east-1'
      AWS_DEFAULT_OUTPUT: json
  zevrant-oauth2-service-db:
    deploy:
      placement:
        constraints:
          - node.labels.usage == db
    networks:
      secret:
        ipv4_address: 173.16.238.1
    volumes:
      - /storage/keys/db/oauth2:/storage/keys/db/oauth2
    ports:
      - "5432:5432"
    image: webhippie/postgresql:latest
    environment:
      PGDATA: /storage/keys/db/oauth2
      POSTGRES_DB: oauth2
      POSTGRES_USER: zevrant
      POSTGRES_PASSWORD:
networks:
  microservices:
    external:
      name: zevrant-discovery-service_microservices
  secret:
    # use the bridge driver, but enable IPv6
    driver: overlay
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 173.16.238.0/28

