version: '3.5'
services:
  zevrant-oauth2-service:
    ports:
      - "9001:9001"
    restart: unless-stopped
    image: zevrant/zevrant-oauth2-service:0.0.10
    deploy:
      placement:
        constraints:
          - node.role == worker
    environment:
      VERSION:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      AWS_DEFAULT_REGION: 'us-east-1'
      AWS_DEFAULT_OUTPUT: json
#networks:
#  default:
#    external:
#      name: microservices

