version: '3.5'
services:
  zevrant-oauth2-service:
    ports:
      - "9001:9001"
    restart: unless-stopped
    image: zevrant/zevrant-oauth2-service:${VERSION}
    deploy:
      placement:
        constraints:
          - node.role == worker
    environment:
      VERSION:
      AWS_ACCESS_KEY_ID: AKIA2RW3K76J2J7GULPY
      AWS_SECRET_ACCESS_KEY: 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
      AWS_DEFAULT_REGION: 'us-east-1'
      AWS_DEFAULT_OUTPUT: json
networks:
  default:
    external:
      name: microservices

