oauth2:
  keystore:
    alias: 1

zevrant:
  bucketName: 'zevrant-resources'
  keystore: 'prod/ssl/keystore.p12'
  ssl:
    key-store: /storage/keys/zevrant-services.p12
    key-store-password: ${ssl.keystore.password}

logging:
  level:
    root: ERROR
    net.zevrant.services.zevrant.oauth2.service: ERROR

eureka:
  instance:
    prefer-ip-address: true
    hostname: ${IP_ADDRESS}
    ip-address: ${IP_ADDRESS}
  client:
    serviceUrl:
      defaultZone:  http://172.16.238.10:8999/eureka/
