spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: local
  datasource:
    url: 'jdbc:postgresql://database-2.cpvhgxlcfvwx.us-east-1.rds.amazonaws.com:5432/oauth2'
    username: 'zevrant'
    password: ${rds.oauth.password}
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: ERROR
    net.zevrant.services.zevrant.oauth2.service: ERROR

eureka:
  client:
    serviceUrl:
      defaultZone:  http://172.16.238.10:8999/eureka/
