spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: 'jdbc:postgresql://${ZEVRANT_OAUTH2_SERVICE_DB_SERVICE_HOST}:${ZEVRANT_OAUTH2_SERVICE_DB_SERVICE_PORT}/oauth2'
    username: 'zevrant'
    password: ${rds.oauth2.password}
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: false

zevrant:
  bucketName:
  keystore:
  ssl:
    key-store: ./zevrant-services.p12
    key-store-password: ${password}