datasource:
  url: jdbc:postgresql://database-2.cpvhgxlcfvwx.us-east-1.rds.amazonaws.com:5432/oauth2
  username: zevrant
  password: ${rds.oauth.password}
jpa:
  show-sql: true
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: ERROR
    net.zevrant.services.zevrant.oauth2.service: ERROR