spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: 'jdbc:postgresql://zevrant-oauth2-service-db:5432/oauth2'
    username: 'zevrant'
    password: ${rds.oauth2.password}
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  ssl:
    key-store: /usr/local/microservices/zevrant-home-services/zevrant-oauth2-service/zevrant-services.p12
    key-store-type: PKCS12
    key-store-password: ${password}


zevrant:
  ssl:
    key-store: /usr/local/microservices/zevrant-home-services/zevrant-oauth2-service/zevrant-services.p12
    key-store-password: ${password}


