spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://localhost:5432/oauth2?createDatabaseIfNotExist=true
    username: sa
    password: example
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: zevrant-oauth2-service
  liquibase:
    enabled: true

server:
  port: 9001
  servlet:
    context-path: /${spring.application.name}
  ssl:
    key-store: /storage/keys/zevrant-services.p12
    key-store-type: PKCS12
    key-store-password: ${ssl.keystore.password}
oauth2:
  keystore:
    alias: 1

zevrant:
  ssl:
    key-store: /storage/keys/zevrant-services.p12
    key-store-password: ${ssl.keystore.password}
  bucketName:
  keystore:
  encrypted:
    properties: ssl/keystore/password,rds/oauth2/password

context:
  initializer:
    classes: net.zevrant.services.security.common.secrets.management.services.EncryptedPropertyContextInitializer

management:
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    ldap:
      enabled: false


logging:
  level:
    root: error
    net.zevrant.services: debug