spring:
  webflux:
    base-path: /zevrant-oauth2-service
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: local
  application:
    name: zevrant-oauth2-service
  aop:
    proxy-target-class: true
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: https://172.16.0.1:9011/auth/realms/zevrant-services-local
        registration:
          keycloak:
            client-id: ${zevrant.services.oauth.clientId}
            client-secret: ${zevrant.services.oauth.clientSecret}
      resourceserver:
        jwt:
          issuer-uri: ${spring.security.oauth2.client.provider.keycloak.issuer-uri}


server:
  port: 9001
  ssl:
    key-store: /storage/keys/zevrant-services.p12
    key-store-type: PKCS12
    key-store-password: ${password}
oauth2:
  keystore:
    alias: 1

zevrant:
  services:
    keycloak:
      baseUrl: 'https://localhost:9011/auth'
    oauth:
      clientId: ${oauth.oauth.clientId}
      clientSecret: ${oauth.oauth.clientSecret}
  encrypted:
    properties: oauth/oauth/clientId,oauth/oauth/clientSecret,oauth/admin/clientId,oauth/admin/clientSecret

context:
  initializer:
    classes: com.zevrant.services.zevrantsecuritycommon.services.EncryptedPropertyContextInitializer

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  health:
    ldap:
      enabled: false


logging:
  level:
    root: info
    com.zevrant.services: debug
