spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: local
  datasource:
    url: 'jdbc:postgresql://zevrant-oauth2-service_zevrant-oauth2-service-db:5432/oauth2'
    username: 'zevrant'
    password: ${rds.oauth.password}
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

oauth2:
  keystore:
    alias: 1

zevrant:
  bucketName: 'zevrant-resources'
  keystore: 'prod/ssl/oauth/zevrant-services.p12'
  ssl:
    key-store: ./zevrant-services.p12
    key-store-password: ${password}

logging:
  level:
    root: ERROR
    net.zevrant.services.zevrant.oauth2.service: ERROR

eureka:
  instance:
    prefer-ip-address: true
    hostname: ${IP_ADDRESS}
    ip-address: ${IP_ADDRESS}
  client:
    serviceUrl:
      defaultZone:  http://172.16.238.10:8999/eureka/
