spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: local
  datasource:
    url: 'jdbc:postgresql://database-2.cpvhgxlcfvwx.us-east-1.rds.amazonaws.com:5432/oauth2'
    username: 'zevrant'
    password: ${rds.oauth.password}
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

oauth2:
  keystore:
    alias: 1

context:
  initializer:
    classes: net.zevrant.services.security.common.secrets.management.services.EncryptedPropertyContextInitializer

zevrant:
  bucketName: 'zevrant-resources'
  keystore: 'prod/ssl/keystore.p12'
  ssl:
    key-store: /storage/keys/zevrant-services.p12
    key-store-password: ${ssl.keystore.password}

logging:
  level:
    root: ERROR
    net.zevrant.services.zevrant.oauth2.service: ERROR

eureka:
  instance:
    non-secure-port-enabled: false
    secure-port-enabled: true
    secure-port: ${server.port}
    home-page-url: https://${eureka.instance.hostname}:${server.port}/
  client:
    serviceUrl:
      defaultZone:  http://172.16.238.10:8999/eureka/
