spring:
  profiles:
    active: local

  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    driver-class: org.h2.Driver
    username: sa    
    password: sa
server:
  port: 9001
  servlet:
    context-path: /zevrant-oauth2-service


zevrant:
    oauth:
      clients:
        users:
          - client-id: test
            client-secret: '{noop}test'
            grant-types:
              - client_credentials
            scopes:
              - DEFAULT
            redirect-uris: localhost:8080
            granted-authorities:
              - DEFAULT
            access-token-validity-seconds: 300
            refresh-token-validity-seconds: 300
            auto-approve: true
            additional-information:
              -
security:
  oauth2:
    client:
      access-token-uri: /oauth/token