spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: https://zevrant-services.com/auth/realms/zevrant-services-prod
        registration:
          keycloak:
            client-id: ${zevrant.services.oauth.clientId}
            client-secret: ${zevrant.services.oauth.clientSecret}
      resourceserver:
        jwt:
          issuer-uri: ${spring.security.oauth2.client.provider.keycloak.issuer-uri}

server:
  ssl:
    key-store: /usr/local/microservices/zevrant-home-services/zevrant-oauth2-service/zevrant-services.p12
    key-store-type: PKCS12
    key-store-password: ${password}


zevrant:
  ssl:
    key-store: /usr/local/microservices/zevrant-home-services/zevrant-oauth2-service/zevrant-services.p12
    key-store-password: ${password}


logging:
  level:
    root: info
    com.zevrant.services: info
