server:
  ssl:
    key-store: /usr/local/microservices/zevrant-home-services/zevrant-oauth2-service/zevrant-services.p12
    key-store-type: PKCS12
    key-store-password: ${password}

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: 'jdbc:postgresql://${ZEVRANT_OAUTH2_SERVICE_DB_SERVICE_HOST}:${ZEVRANT_OAUTH2_SERVICE_DB_SERVICE_PORT}/oauth2'
    username: 'zevrant'
    password: ${rds.oauth2.password}
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

zevrant:
  bucketName:
  keystore:
  ssl:
    key-store: /usr/local/microservices/zevrant-home-services/zevrant-oauth2-service/zevrant-services.p12
    key-store-password: ${password}

logging:
  level:
    root: INFO
    net.zevrant.services.zevrant.oauth2.service: INFO