spring:
  profiles:
    active: local

  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    driver-class: org.h2.Driver
    username: sa    
    password: sa
server:
  port: 9001
  servlet:
    context-path: /zevrant-oauth2-service/

zevrant:
    users:
      - clientId: test
        clientSecret: test
